import "./globals.css";
import { Providers } from "../store/Providers"; // ✅ Fix this line


import {Onest} from "next/font/google"
import { ToastContainer } from "react-toastify";

const onest = Onest({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'], // include weights you use
  display: 'swap',
});
export const metadata = {
  title: "Edu-wire CRM",
  description: "Generated by edu-wire team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={onest.className}>
      <body>
        <Providers>
           <ToastContainer position="top-right" />
          {children}
          </Providers>
      </body>
    </html>
  );
}
