import "./globals.css";
import { Providers } from "../store/Providers"; // ✅ Fix this line


export const metadata = {
  title: "Edu-wire CRM",
  description: "Generated by edu-wire team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
